using System.Text;
using Tedd.MOS65xx.Emulator.Media;
using Tedd.MOS65xx.Emulator.Tools;

namespace Tedd.MOS65xx.Web.Demo;

/// <summary>
/// The built-in tech demo: a self-contained machine code program that is assembled at runtime with
/// <see cref="Assembler"/> and injected through <c>EmulatorSession.AttachProgram</c>.
///
/// <para>What it does (all driven by one raster interrupt per frame, no KERNAL/BASIC code involved once it
/// runs, so it works with OpenROMs as well as the original ROMs):</para>
/// <list type="bullet">
/// <item>Banks out BASIC and KERNAL ($01 = $35), installs its own IRQ/NMI vectors in RAM and disables the
/// CIA timer interrupts, so the demo owns the machine and runs forever until reset.</item>
/// <item>Raster colour bars: the IRQ handler waits for every raster line of the display area and writes a
/// colour from a 256-entry table to $D020/$D021; the table offset advances every frame so the bars move.</item>
/// <item>A hardware-scrolled text scroller on the bottom text row (XSCROLL + 38 column mode switched in the
/// right border of the line above it).</item>
/// <item>Four sprites moving on Lissajous paths (sine tables, 9-bit X positions).</item>
/// <item>A three voice SID tune: bass (sawtooth, percussive envelope), a fast arpeggio (pulse) and a lead
/// (pulse), sequenced at 50 Hz with 6 frames per step over a four chord progression.</item>
/// </list>
/// </summary>
public static class DemoProgram
{
    /// <summary>Load address of the generated PRG (BASIC start, so it can also be saved and RUN normally).</summary>
    public const ushort LoadAddress = 0x0801;

    private const int SpriteBlock = 0x0840 / 64;           // sprite data at $0840 (64-byte block 33)
    private const int CodeStart = 0x0880;
    private const int ScrollRow = 0x07C0;                  // screen row 24
    private const string ScrollText =
        "   TEDD.MOS65XX - A CYCLE-EXACT COMMODORE 64 EMULATOR WRITTEN IN C#. " +
        "THIS DEMO WAS ASSEMBLED IN YOUR BROWSER A MOMENT AGO AND IS RUNNING ON THE EMULATED 6510: " +
        "RASTER INTERRUPTS, COLOUR BARS, HARDWARE SCROLLING, SPRITES AND A THREE VOICE SID TUNE. " +
        "THE VIC-II, CIA AND SID ARE MODELLED PER CYCLE; THE 6502 CORE IS VERIFIED AGAINST 2.56 MILLION " +
        "SINGLESTEPTESTS VECTORS. PRESS RESET TO RETURN TO BASIC.   ";

    /// <summary>Assembles the demo and returns it as a PRG file (2-byte load address header + data).</summary>
    public static byte[] BuildPrg()
    {
        var result = Assembler.Assemble(Source(), LoadAddress);
        if (result.Origin != LoadAddress || result.Labels["start"] != CodeStart)
            throw new InvalidOperationException("Demo layout mismatch: the BASIC stub SYS address does not match the code start");
        return new PrgFile(result.Origin, result.Bytes).ToBytes();
    }

    /// <summary>The assembly source (exposed so the site can show it).</summary>
    public static string Source()
    {
        var sb = new StringBuilder();
        sb.AppendLine("; Tedd.MOS65xx tech demo - generated by DemoProgram.cs, assembled with Tedd.MOS65xx.Emulator.Tools.Assembler");
        sb.AppendLine("frame   = $fb            ; frame counter (also colour bar offset)");
        sb.AppendLine("xscroll = $fc            ; $D016 value for the scroller row ($C0 | 0..7)");
        sb.AppendLine("step    = $fd            ; frames left in the current music step");
        sb.AppendLine("pos     = $fe            ; music position 0..63");
        sb.AppendLine("arpi    = $f7            ; arpeggio note index 0..2");
        sb.AppendLine("tmp     = $f6");
        sb.AppendLine("msb     = $f5            ; sprite X MSBs being assembled");
        sb.AppendLine("tptr    = $f8            ; pointer to the next scroll text character");
        sb.AppendLine();
        sb.AppendLine("* = $0801");
        sb.AppendLine("; BASIC stub: 10 SYS2176");
        sb.AppendLine($".byte $0b,$08,$0a,$00,$9e,\"{CodeStart}\",$00,$00,$00");
        sb.AppendLine($".res $0840-$080d");
        sb.AppendLine("; sprite data (block 33)");
        sb.Append("ball:").AppendLine(Bytes(BallSprite()));
        sb.AppendLine(".byte 0");
        sb.AppendLine();
        sb.AppendLine("""
start:
        sei
        lda #$35                ; RAM at $A000-$BFFF and $E000-$FFFF, I/O at $D000
        sta $01
        lda #$7f                ; no CIA interrupts
        sta $dc0d
        sta $dd0d
        lda $dc0d               ; acknowledge whatever is pending
        lda $dd0d
        lda #<irq               ; our own vectors (the KERNAL is banked out)
        sta $fffe
        lda #>irq
        sta $ffff
        lda #<nmi
        sta $fffa
        lda #>nmi
        sta $fffb
        lda #<start
        sta $fffc
        lda #>start
        sta $fffd

        ; --- screen ---
        ldx #0
        lda #$20
clr:    sta $0400,x
        sta $0500,x
        sta $0600,x
        sta $0700,x
        inx
        bne clr
        lda #1
ccl:    sta $d800,x
        sta $d900,x
        sta $da00,x
        sta $db00,x
        inx
        bne ccl
        jsr texts
        lda #<text
        sta tptr
        lda #>text
        sta tptr+1

        ; --- VIC ---
        lda $dd00
        ora #$03                ; VIC bank 0
        sta $dd00
        lda #$15                ; screen $0400, charset $1000
        sta $d018
        lda #$c0                ; 38 columns (the scroller needs them), no scroll, hires text
        sta $d016
        sta xscroll
        lda #$1b                ; display on, 25 rows, YSCROLL 3, raster IRQ line < 256
        sta $d011
        lda #47                 ; raster IRQ a few lines above the display window (line 50)
        sta $d012
        lda #0
        sta $d020
        sta $d021
        sta $d017               ; no sprite expansion
        sta $d01d
        sta $d01c               ; no multicolour sprites
        sta $d01b               ; sprites in front of text
        sta $d010
        lda #$0f                ; sprites 0-3 on
        sta $d015
        lda #1
        sta $d027
        lda #7
        sta $d028
        lda #3
        sta $d029
        lda #10
        sta $d02a
""");
        sb.AppendLine($"        lda #{SpriteBlock}");
        sb.AppendLine("""
        sta $07f8
        sta $07f9
        sta $07fa
        sta $07fb

        ; --- SID ---
        ldx #$18
        lda #0
sclr:   sta $d400,x
        dex
        bpl sclr
        lda #$0f                ; full volume, no filter
        sta $d418
        lda #$08                ; voice 1 (bass): attack 0, decay 300 ms, sustain 0
        sta $d405
        lda #$00
        sta $d406
        lda #$00                ; voice 2 (arpeggio): pulse 25 %, sustain 8
        sta $d409
        lda #$04
        sta $d40a
        lda #$00
        sta $d40c
        lda #$88
        sta $d40d
        lda #$41
        sta $d40b
        lda #$00                ; voice 3 (lead): pulse ~19 %, attack 0, decay 1.5 s, sustain 6, release 1.5 s
        sta $d410
        lda #$03
        sta $d411
        lda #$0a
        sta $d413
        lda #$6a
        sta $d414

        lda #0
        sta frame
        sta pos
        sta arpi
        lda #1
        sta step

        lda #1                  ; raster interrupt on
        sta $d01a
        lda $d019
        sta $d019
        cli
idle:   jmp idle

; ------------------------------------------------------------------ interrupt, once per frame at line 47
irq:    pha
        txa
        pha
        tya
        pha
        lda $d019
        sta $d019               ; acknowledge
        lda #$c0
        sta $d016
w49:    lda $d012
        cmp #49
        bne w49
        ldx frame               ; colour table offset
        ldy #200                ; lines 50..249
bar:    lda $d012
wl:     cmp $d012
        beq wl                  ; wait for the next raster line
        lda bars,x
        sta $d020
        sta $d021
        inx
        cpy #9                  ; line 241, the last line of row 23:
        bne nosw
        lda #5                  ; wait until the right border, then set XSCROLL for the scroller row
dly:    sec
        sbc #1
        bne dly
        lda xscroll
        sta $d016
nosw:   dey
        bne bar
        lda #$c0                ; bottom border: no scroll again
        sta $d016
        lda #0
        sta $d020
        sta $d021
        inc frame
        jsr scroll
        jsr sprites
        jsr music
        pla
        tay
        pla
        tax
        pla
nmi:    rti

; ------------------------------------------------------------------ scroller (row 24)
scroll: lda xscroll
        and #7
        beq shift
        dec xscroll
        rts
shift:  lda #$c7
        sta xscroll
        ldx #0
""");
        sb.AppendLine($"sh:     lda ${ScrollRow + 1:x4},x");
        sb.AppendLine($"        sta ${ScrollRow:x4},x");
        sb.AppendLine("""
        inx
        cpx #39
        bne sh
        ldy #0
        lda (tptr),y
        bne ok
        lda #<text              ; wrap around
        sta tptr
        lda #>text
        sta tptr+1
        lda (tptr),y
""");
        sb.AppendLine($"ok:     sta ${ScrollRow + 39:x4}");
        sb.AppendLine("""
        inc tptr
        bne sdone
        inc tptr+1
sdone:  rts

; ------------------------------------------------------------------ sprites (Lissajous paths)
sprites:
        lda #0
        sta msb
        ldx #0                  ; sprite 0..3
sp:     txa
        asl
        asl
        asl
        asl
        asl                     ; (sprite * 2) * 32 = sprite * 64 = phase offset
        sta tmp
        lda frame
        asl
        clc
        adc tmp
        tay
        lda xlo,y
        sta $d000,x             ; X (x = sprite*2 below, see inx inx)
        lda xhi,y
        beq nomsb
        lda bmask,x
        ora msb
        sta msb
nomsb:  lda frame
        clc
        adc frame
        clc
        adc frame               ; frame * 3
        clc
        adc tmp
        tay
        lda ysin,y
        sta $d001,x
        inx
        inx
        cpx #8
        bne sp
        lda msb
        sta $d010
        rts
bmask:  .byte 1,0,2,0,4,0,8,0

; ------------------------------------------------------------------ music (50 Hz, 6 frames per step)
music:  lda pos
        lsr
        lsr
        lsr
        lsr
        asl
        asl                     ; chord * 4
        clc
        adc arpi
        tax
        lda chordn,x            ; arpeggio note for this frame
        tax
        lda freqlo,x
        sta $d407
        lda freqhi,x
        sta $d408
        inc arpi
        lda arpi
        cmp #3
        bne arpok
        lda #0
        sta arpi
arpok:  dec step
        beq newstep
        rts
newstep:
        lda #6
        sta step
        ldx pos
        lda melody,x            ; --- lead
        cmp #255
        beq nolead              ; hold
        cmp #0
        bne leadon
        lda #$40                ; rest: gate off
        sta $d412
        jmp nolead
leadon: tay
        lda #$40
        sta $d412
        lda freqlo,y
        sta $d40e
        lda freqhi,y
        sta $d40f
        lda #$41
        sta $d412
nolead: txa                     ; --- bass
        and #15
        tay
        lda basspat,y
        cmp #255
        beq nobass
        sta tmp
        txa
        lsr
        lsr
        lsr
        lsr
        tay
        lda chordr,y
        clc
        adc tmp
        tay
        lda #$20
        sta $d404
        lda freqlo,y
        sta $d400
        lda freqhi,y
        sta $d401
        lda #$21
        sta $d404
nobass: txa                     ; --- retrigger the arpeggio on chord changes
        and #15
        bne noret
        lda #$40
        sta $d40b
        lda #$41
        sta $d40b
noret:  inx
        txa
        and #63
        sta pos
        rts

; ------------------------------------------------------------------ static texts
texts:
""");
        foreach (var (row, col, colour, text) in TitleLines())
        {
            int addr = 0x0400 + row * 40 + col;
            string label = $"t{row}";
            sb.AppendLine($"        ldx #0");
            sb.AppendLine($"{label}:   lda {label}d,x");
            sb.AppendLine($"        sta ${addr:x4},x");
            sb.AppendLine($"        lda #{colour}");
            sb.AppendLine($"        sta ${0xD800 + row * 40 + col:x4},x");
            sb.AppendLine($"        inx");
            sb.AppendLine($"        cpx #{text.Length}");
            sb.AppendLine($"        bne {label}");
        }
        sb.AppendLine("        rts");
        foreach (var (row, _, _, text) in TitleLines())
            sb.Append($"t{row}d:").AppendLine(Bytes(ScreenCodes(text)));
        sb.AppendLine();
        sb.AppendLine("; ------------------------------------------------------------------ tables");
        sb.Append("text:").AppendLine(Bytes(ScreenCodes(ScrollText))).AppendLine(".byte 0");
        sb.Append("bars:").AppendLine(Bytes(BarTable()));
        var (xlo, xhi, ysin) = SineTables();
        sb.Append("xlo:").AppendLine(Bytes(xlo));
        sb.Append("xhi:").AppendLine(Bytes(xhi));
        sb.Append("ysin:").AppendLine(Bytes(ysin));
        var (lo, hi) = FrequencyTables();
        sb.Append("freqlo:").AppendLine(Bytes(lo));
        sb.Append("freqhi:").AppendLine(Bytes(hi));
        // chords: Am, F, C, G (root in the bass octave; arpeggio notes one octave up)
        int[] roots = { 45, 41, 48, 43 };
        var chordNotes = new List<byte>();
        foreach (var r in roots)
        {
            bool major = r is 41 or 48 or 43;
            chordNotes.Add((byte)(r + 12));
            chordNotes.Add((byte)(r + 12 + (major ? 4 : 3)));
            chordNotes.Add((byte)(r + 12 + 7));
            chordNotes.Add((byte)(r + 24));
        }
        sb.Append("chordn:").AppendLine(Bytes(chordNotes.ToArray()));
        sb.Append("chordr:").AppendLine(Bytes(roots.Select(r => (byte)(r - 12)).ToArray()));
        sb.Append("basspat:").AppendLine(Bytes(new byte[] { 0, 255, 0, 0, 255, 0, 7, 255, 0, 255, 0, 0, 255, 12, 7, 255 }));
        sb.Append("melody:").AppendLine(Bytes(new byte[]
        {
            76, 255, 72, 255, 74, 255, 76, 255, 72, 255, 69, 255, 255, 255, 71, 255,   // Am
            72, 255, 69, 255, 72, 255, 74, 255, 76, 255, 255, 255, 74, 255, 72, 255,   // F
            71, 255, 72, 255, 74, 255, 76, 255, 79, 255, 76, 255, 74, 255, 72, 255,   // C
            74, 255, 71, 255, 67, 255, 71, 255, 74, 255, 255, 255, 76, 255, 74, 255,   // G
        }));
        return sb.ToString();
    }

    private static IEnumerable<(int Row, int Col, int Colour, string Text)> TitleLines()
    {
        yield return (2, 14, 7, "TEDD.MOS65XX");
        yield return (4, 5, 1, "CYCLE-EXACT COMMODORE 64 IN C#");
        yield return (6, 2, 15, "6510 + VIC-II + CIA + SID, PER CYCLE");
        yield return (8, 1, 15, "RUNNING IN YOUR BROWSER (BLAZOR WASM)");
        yield return (20, 4, 13, "RASTER IRQ - SPRITES - SID MUSIC");
        yield return (22, 8, 12, "PRESS RESET TO EXIT DEMO");
    }

    /// <summary>ASCII (upper case) to C64 screen codes for the upper-case/graphics character set.</summary>
    public static byte[] ScreenCodes(string text)
    {
        var bytes = new byte[text.Length];
        for (int i = 0; i < text.Length; i++)
        {
            char c = char.ToUpperInvariant(text[i]);
            bytes[i] = c switch
            {
                >= 'A' and <= 'Z' => (byte)(c - 'A' + 1),
                '@' => 0,
                '[' => 27,
                ']' => 29,
                >= ' ' and <= '?' => (byte)c,
                _ => 32,
            };
        }
        return bytes;
    }

    private static byte[] BallSprite()
    {
        // 24x21 hires sprite: a filled circle with a small highlight
        var data = new byte[63];
        const double cx = 11.5, cy = 10.0, r = 9.5;
        for (int y = 0; y < 21; y++)
        {
            for (int x = 0; x < 24; x++)
            {
                double dx = x - cx, dy = y - cy;
                bool on = dx * dx + dy * dy <= r * r;
                double hx = x - 8.5, hy = y - 6.5;
                if (hx * hx + hy * hy <= 4.0) on = false; // highlight hole
                if (on) data[y * 3 + x / 8] |= (byte)(0x80 >> (x & 7));
            }
        }
        return data;
    }

    private static byte[] BarTable()
    {
        // four 32-line bars (16 lines of colour ramp + 16 lines black) = 256 entries
        int[][] ramps =
        {
            new[] { 6, 6, 4, 4, 14, 14, 3, 3, 3, 3, 14, 14, 4, 4, 6, 6 },      // blue
            new[] { 2, 2, 8, 8, 10, 10, 7, 7, 7, 7, 10, 10, 8, 8, 2, 2 },      // red
            new[] { 9, 9, 5, 5, 13, 13, 1, 1, 1, 1, 13, 13, 5, 5, 9, 9 },      // green
            new[] { 11, 11, 12, 12, 15, 15, 1, 1, 1, 1, 15, 15, 12, 12, 11, 11 }, // grey
        };
        var table = new byte[256];
        int o = 0;
        foreach (var ramp in ramps)
        {
            foreach (var c in ramp) table[o++] = (byte)c;
            o += 16;
        }
        return table;
    }

    private static (byte[] XLo, byte[] XHi, byte[] Y) SineTables()
    {
        var xlo = new byte[256];
        var xhi = new byte[256];
        var y = new byte[256];
        for (int i = 0; i < 256; i++)
        {
            double s = (Math.Sin(i * Math.PI * 2 / 256) + 1) / 2;
            int x = 24 + (int)Math.Round(s * 296);   // 24..320: fully visible sprite X range
            xlo[i] = (byte)x;
            xhi[i] = (byte)(x >> 8);
            y[i] = (byte)(50 + (int)Math.Round(s * 168));  // 50..218: keeps sprites off lines 241/242 (scroller timing)
        }
        return (xlo, xhi, y);
    }

    private static (byte[] Lo, byte[] Hi) FrequencyTables()
    {
        // SID frequency register for MIDI notes 0..95 (PAL clock)
        var lo = new byte[96];
        var hi = new byte[96];
        for (int n = 0; n < 96; n++)
        {
            double f = 440.0 * Math.Pow(2, (n - 69) / 12.0);
            int v = (int)Math.Round(f * 16777216.0 / 985248.0);
            if (v > 0xFFFF) v = 0xFFFF;
            lo[n] = (byte)v;
            hi[n] = (byte)(v >> 8);
        }
        return (lo, hi);
    }

    private static string Bytes(byte[] data)
    {
        var sb = new StringBuilder();
        for (int i = 0; i < data.Length; i += 16)
        {
            sb.AppendLine();
            sb.Append("        .byte ");
            sb.Append(string.Join(",", data.Skip(i).Take(16).Select(b => "$" + b.ToString("x2"))));
        }
        return sb.ToString();
    }
}
